In [1]:
import pandas as pd
from lib.helper import load_coin_data

In [2]:
df = load_coin_data(data_file='../data/crypto-markets.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 942294 entries, 224703 to 776162
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   slug         942294 non-null  object
 1   symbol       942294 non-null  object
 2   name         942294 non-null  object
 3   date         942294 non-null  datetime64[ns]
 4   ranknow      942294 non-null  int64
 5   open         942294 non-null  float64
 6   high         942294 non-null  float64
 7   low          942294 non-null  float64
 8   close        942294 non-null  float64
 9   volume       942294 non-null  float64
 10  market       942294 non-null  float64
 11  close_ratio  942294 non-null  float64
 12  spread       942294 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(3)
memory usage: 100.6+ MB

In [3]:
df.head()

,slug,symbol,name,date,ranknow,open,high,low,close,volume,market,close_ratio,spread
224703,0chain,ZCN,0chain,2018-11-29,441,0.107484,0.108201,0.096704,0.102817,169073.0,4112664.0,0.5317,0.01
224702,0chain,ZCN,0chain,2018-11-28,441,0.094331,0.108899,0.088493,0.106128,96018.0,4245120.0,0.8642,0.02
224701,0chain,ZCN,0chain,2018-11-27,441,0.092206,0.096801,0.064615,0.094085,91734.0,3763416.0,0.9156,0.03
224700,0chain,ZCN,0chain,2018-11-26,441,0.103348,0.103859,0.087432,0.094182,91966.0,3767272.0,0.4109,0.02
224699,0chain,ZCN,0chain,2018-11-25,441,0.091283,0.114487,0.077672,0.103559,94287.0,4142360.0,0.7032,0.04

In [4]:
df.tail()

,slug,symbol,name,date,ranknow,open,high,low,close,volume,market,close_ratio,spread
776166,zurcoin,ZUR,Zurcoin,2016-05-13,1596,0.000077,0.000086,0.000023,0.000036,28.0,2387.0,0.2063,0.0
776165,zurcoin,ZUR,Zurcoin,2016-05-12,1596,0.000122,0.000140,0.000063,0.000077,24.0,5061.0,0.1818,0.0
776164,zurcoin,ZUR,Zurcoin,2016-05-11,1596,0.000032,0.000145,0.000032,0.000122,369.0,7998.0,0.7965,0.0
776163,zurcoin,ZUR,Zurcoin,2016-05-10,1596,0.000055,0.000055,0.000023,0.000032,6.0,2064.0,0.2812,0.0
776162,zurcoin,ZUR,Zurcoin,2016-05-09,1596,0.000055,0.000055,0.000055,0.000055,24.0,3611.0,0.0000,0.0

In [4]:
# only work on 'bitcoin' 
df = df[df['slug'].isin(['bitcoin', 'litecoin'])]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4084 entries, 0 to 9828
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   slug         4084 non-null   object
 1   symbol       4084 non-null   object
 2   name         4084 non-null   object
 3   date         4084 non-null   datetime64[ns]
 4   ranknow      4084 non-null   int64
 5   open         4084 non-null   float64
 6   high         4084 non-null   float64
 7   low          4084 non-null   float64
 8   close        4084 non-null   float64
 9   volume       4084 non-null   float64
 10  market       4084 non-null   float64
 11  close_ratio  4084 non-null   float64
 12  spread       4084 non-null   float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(3)
memory usage: 446.7+ KB

In [13]:
tmp = df.groupby('slug').apply(lambda x: x.sort_values('date', ascending=False)).reset_index()
tmp.head()

/var/folders/dq/j2p0trqj0_9dbtsdc6t21fnw0000gn/T/ipykernel_12075/4229869176.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tmp = df.groupby('slug').apply(lambda x: x.sort_values('date', ascending=False)).reset_index()

ValueError: cannot insert slug, already exists

In [12]:
tmp.tail()

                   slug symbol      name       date  ranknow  open  high  \
slug
litecoin 7791  litecoin    LTC  Litecoin 2013-05-02        7  3.78  4.04
         7790  litecoin    LTC  Litecoin 2013-05-01        7  4.29  4.36
         7789  litecoin    LTC  Litecoin 2013-04-30        7  4.40  4.57
         7788  litecoin    LTC  Litecoin 2013-04-29        7  4.37  4.57
         7787  litecoin    LTC  Litecoin 2013-04-28        7  4.30  4.40

                low  close  volume      market  close_ratio  spread
slug
litecoin 7791  3.01   3.37     0.0  58287979.0       0.3495    1.03
         7790  3.52   3.80     0.0  65604596.0       0.3333    0.84
         7789  4.17   4.30     0.0  74020918.0       0.3250    0.40
         7788  4.23   4.38     0.0  75388964.0       0.4412    0.34
         7787  4.18   4.35     0.0  74636938.0       0.7727    0.22

In [7]:
#
# code used to find the gap between number of slugs vs number of symbols
#

# for slug in df['slug'].unique():
#     if len(df[df.slug == slug]['name'].unique()) > 1:
#         print(f"{slug}: {df[df.slug == slug]['name'].unique()}")